### ISSUE TITLE
ScanNetv2数据集训练时间

### ISSUE THREAD

**Issue by Jul-Wooo** [Matrix-ASC/DeLA_v2#1]
作者您好，感谢您的开源项目。我想请教一下，在ScanNetv2数据集是如何在八个小时左右训练完成的，我训练了两次，基本都是在十二三个小时，您是使用了什么方法来提升训练速度吗？

**Comment by binjiechen** [comment]
你好，代码都是一样的啊，只是硬件可能不同。我是4090+13600k。我不知道你的硬件配置是什么。如果你的瓶颈是cpu，你可以尝试把数据集加载的num_workers改高（如果你服务器的cpu有更多核数可用）。

**Comment by Jul-Wooo** [comment]
我把num_workers调高以后问题解决了，非常感谢您的建议！
